#!/bin/bash
set -eu
set -o pipefail

cd "$(dirname "$0")/.."

excluded_files=(
  ".git"
  "scripts"
)

excluded_option=""
for excluded_file in "${excluded_files[@]}"; do
  if [ -n "$excluded_option" ]; then
    excluded_option+=" -and "
  fi
  excluded_option+="-not -path \"./$excluded_file/*\""
done

selected=$(eval "echo \$(find ./ -type f "$excluded_option")" | tr " " "\n" | fzf --preview-window right:70%)
[[ -z "$selected" ]] && exit 0

file=$(basename "$selected")
extension=${file##*.}

case "$extension" in
  "go")
    echo -e "exec: go run $selected\n---"
    go run $selected
    ;;
  *)
    echo "error: not match extension pattern" >&2 && exit 1
    ;;
esac
