#!/bin/bash
set -eu
set -o pipefail

cd "$(dirname "$0")/.."

current_date=$(date '+%Y%m%d')
selected=$(find ./ -type f -path "./code/*" | tr " " "\n" | fzf --preview-window right:70% --query "$current_date")
[[ -z "$selected" ]] && exit 0

file=$(basename "$selected")
extension=${file##*.}

case "$extension" in
  "go")
    echo -e "exec: go run $selected\n---"
    go run $selected
    ;;
  *)
    echo "error: not match extension pattern" >&2 && exit 1
    ;;
esac
