#!/bin/bash
set -e
set -o pipefail

cd "$(dirname "$0")/.."

fzf_query="$1"
current_date=$(date '+%Y%m')
prefix="./code/"
selected=$(
  find ./ -type f -path "$prefix*" | sed "s|$prefix||" | tr " " "\n" | grep -v "_test." \
    | fzf --preview-window right:70% \
      --preview='bat --color=always "./code/$(echo {})"' \
      --query "$current_date $fzf_query"
)
[[ -z "$selected" ]] && exit 0

selected="$prefix/$selected"
file=$(basename "$selected")
extension=${file##*.}

case "$extension" in
  "go")
    ./scripts/go_test $selected
    ;;
  *)
    echo "error: not match extension pattern" >&2 && exit 1
    ;;
esac
